# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.CharField(max_length=60),
        ),
    ]
